baseURL: "/"
languageCode: "nl"
title: "Salon Beauty by Echika"

# Params
params:
  author: Beauty by Echika
  email : info@beautybyechika.nl
  tel: '+0850608912'
  address:  'Beauty by Echika<br>Luringstraat 10<br>9591BD Onstwedde<br>Nederland'
  timings:
    - day:  Maandag
      time: 10:00-17:00
    - day:  Dinsdag
      time: 10:00-17:00
    - day:  Woensdag
      time: 10:00-17:00
    - day:  Donderdag
      time: 10:00-17:00
    - day:  Vrijdag
      time: 10:00-17:00
# build and other other setup
build:
  writeStats: true
markup:
  goldmark:
    renderer:
      unsafe: true
# Menus
# sectionPagesMenu: main
menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Over Ons
      url: 
      weight: 20
    - name: Portfolio
      url: 
      weight: 30
    - name: Afspraak Maken
      url: /afspraak-maken/
      weight: 40
    - name: Shop
      url: https://beautybyechika.nl/nl/
      weight: 50
  social:
    - name: Facebook
      url: https://www.facebook.com/beautybyechika
      pre: fb.png
      weight: 10
    - name: Instagram
      url: https://www.instagram.com/beautybyechika
      pre: insta.png
      weight: 20
    - name: Pintrest
      url: https://www.pinterest.ca/beautybyechika
      pre: pin.png
      weight: 30

security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^babel$
      - ^postcss$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
