[build]
publish = "public"
command = "hugo --gc --minify;"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --minify --gc -d public -b $DEPLOY_PRIME_URL"

  [context.branch-deploy.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = "hugo --gc --buildFuture -D -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_VERSION = "0.111.3"

# headers
[[headers]]
for = "/*.jpg"

  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

  [headers.values]
  Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"